### ISSUE TITLE
Microsoft.Quantum.MachineLearning dependency mismatch

### ISSUE THREAD

**Issue by born-2learn** [microsoft/Quantum#430]
**Facing issues while running the HalfMoonModel example form Microsoft Quantum Docs**
I have tried out this [Microsoft Docs](https://docs.microsoft.com/en-us/quantum/user-guide/libraries/machine-learning/basic-classification?tabs=tabid-python) post for a machine learning application on HalfMoonModel.

**To Reproduce**
1. Run `python host.py` in [this](https://github.com/QPower-Research/qml_qsharp/tree/master/HalfMoonModel) directory
2. `>>> qsharp.__version__`  
`0.12.2008.2513`
3. See error
```
{'text/plain': 'Adding package Microsoft.Quantum.MachineLearning::0.11.2004.2825.', 'application/json': '{"LastUpdated":"2020-09-21T12:46:48.2864566+05:30","IsCompleted":false,"Description":"Adding package Microsoft.Quantum.MachineLearning::0.11.2004.2825","Subtask":null}'}
{'text/plain': 'Reloading workspace.', 'application/json': '{"LastUpdated":"2020-09-21T12:46:48.7294194+05:30","IsCompleted":false,"Description":"Reloading workspace","Subtask":null}'}
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS6104: No namespace with the name "Microsoft.Quantum.Convert" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS6104: No namespace with the name "Microsoft.Quantum.Intrinsic" exists.
Traceback (most recent call last):
  File ".\host.py", line 12, in <module>
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "Mapped" exists.
    qsharp.reload()
  File "C:\Users\farha\anaconda3\envs\qsharp-env\lib\site-packages\qsharp\__init__.py", line 74, in reload
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "Zip" exists.
    client.reload()
  File "C:\Users\farha\anaconda3\envs\qsharp-env\lib\site-packages\qsharp\clients\iqsharp.py", line 128, in reload
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "IntAsDouble" exists.
    return self._execute(f"%workspace reload", raise_on_stderr=True)
  File "C:\Users\farha\anaconda3\envs\qsharp-env\lib\site-packages\qsharp\clients\iqsharp.py", line 252, in _execute
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "IntAsDouble" exists.
    reply = self.kernel_client.execute_interactive(input, output_hook=_output_hook, **kwargs)
  File "C:\Users\farha\anaconda3\envs\qsharp-env\lib\site-packages\jupyter_client\blocking\client.py", line 329, in execute_interactive
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "Length" exists.
    output_hook(msg)
  File "C:\Users\farha\anaconda3\envs\qsharp-env\lib\site-packages\qsharp\clients\iqsharp.py", line 207, in _handle_message
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "Mapped" exists.
    error_callback(msg['content']['text'])
  File "C:\Users\farha\anaconda3\envs\qsharp-env\lib\site-packages\qsharp\clients\iqsharp.py", line 225, in log_error
fail    if msg['msg_type'] == 'stream' and msg['content']['name'] == 'stderr':
: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "Default" exists.
TypeError: string indices must be integers
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "Structure" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "Parameters" exists.

```

**Additional context**
Tried using the `0.12.2008.2513` version of `Microsoft.Quantum.MachineLearning` as well, but still running into issues.

**Comment by rmshaffer** [comment]
Hi @born-2learn, thanks for reporting!

Can you try using the latest version of that sample?
https://github.com/microsoft/Quantum/tree/main/samples/machine-learning/half-moons

The issues you are describing should be addressed in the current version. Specifically, calling `import qsharp` from Python will now automatically read in the `PackageReference` items from `HalfMoons.csproj`, which should fix the problems you're seeing.

**Comment by msoeken** [comment]
Looks like this issue was resolved, and we are closing it for now. Please feel free to reopen the issue, if it still causes problems.
